---
  vagrantfile-local: 
    vm: 
      box: "centos65-x64-vbox43-1383512148"
      box_url: "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"
      hostname: "bitcoinsms.es"
      network: 
        private_network: "192.168.56.133"
        forwarded_port: 
          ssh: 
            host: "5793"
            guest: "22"
          http: 
            host: "80"
            guest: "80"
      provider: 
        virtualbox: 
          modifyvm: 
            natdnshostresolver1: "on"
            memory: "512"
          setextradata: 
            VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
      provision: 
        puppet: 
          manifests_path: "puphpet/puppet"
          manifest_file: "manifest.pp"
          options: 
            - "--verbose"
            - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
            - "--parser future"
      synced_folder: 
        kpNGEk798lib: 
          id: "vagrant-root"
          source: "./"
          target: "/var/www/awesome.dev"
          type: "nfs"
      usable_port_range: "2200..2250"
    ssh: 
      host: null
      port: null
      private_key_path: null
      username: "vagrant"
      password: null
      guest_port: null
      keep_alive: true
      forward_agent: false
      forward_x11: false
      shell: "bash -l"
    vagrant: 
      host: "detect"
  server: 
    packages: 
      - "memcached"
      - "erlang"
      - "mosquitto"
      - "libmosquitto-devel"
      - "libmosquittopp-devel"
    dot_files: 
      - 
        bash_aliases: null
    _prevent_empty: ""
  mailcatcher: 
    install: 0
    settings: 
      smtp_ip: "0.0.0.0"
      smtp_port: 1025
      http_ip: "0.0.0.0"
      http_port: "1080"
      path: "/usr/local/bin"
      log: "/var/log/mailcatcher/mailcatcher.log"
  nginx: 
    vhosts: 
      bitcoinsms.de: 
        ensure: "present"
        server_name: 
          - "bitcoinsms.es"
          - "www.bitcoinsms.es"
        listen_port: 80
        index_files: 
          - "index.php"
          - "index.html"
          - "index.htm"
        www_root: "/var/www/bitcoinsms.de/app/webroot"
        access_log: "/var/log/nginx/log/bitcoinsms.de.access.log"
        error_log: "/var/log/nginx/log/bitcoinsms.de.error.log"
    locations: 
      bitcoinsms.de-/: 
        ensure: "present"
        vhost: "bitcoinsms.de"
        www_root: "/var/www/bitcoinsms.de/app/webroot"
        location: "~ ^/"
        index_files: 
          - "index.php"
          - "index.html"
          - "index.htm"
        try_files: 
          - "$uri"
          - "$uri/"
          - "/index.php?$args"
      bitcoinsms.de-/*.php: 
        ensure: "present"
        vhost: "bitcoinsms.de"
        location: "~* \\.php$"
        fastcgi: "%{::fastcgi_pass}"
        www_root: "/var/www/bitcoinsms.de/app/webroot"
        index_files: 
          - "index.php"
          - "index.html"
          - "index.htm"
        try_files: 
          - "$uri =404"
        location_cfg_append: 
          fastcgi_connect_timeout: "3m"
          fastcgi_read_timeout: "3m"
          fastcgi_send_timeout: "3m"
      bitcoinsms.de-static: 
        ensure: "present"
        vhost: "bitcoinsms.de"
        location: "~* \\.(ico|3gp|gif|jpg|cur|svg|jpeg|png|wmv|avi|asf|asx|mpg|mpeg|mp4|woff|pls|mp3|mid|wav|swf|flv|js|html|htm|txt|css|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso|htc)(\\?[0-9]+)?$"
        www_root: "/var/www/bitcoinsms.de/app/webroot"
        location_cfg_append: 
          expires: "max"
          access_log: "off"
          log_not_found: "off"
          error_log: "off"
          add_header: "Pragma \"public\""
  nodejs: 
    install: 1
    proxy: false
    version: "present"
    dev_package: true
    manage_repo: false
  nodejs_packages: 
    cordova: 
      ensure: "present"
      provider: "npm"
      require: "Class[nodejs]"
    grunt-cli: 
      ensure: "present"
      provider: "npm"
      require: "Class[nodejs]"
    yo: 
      ensure: "present"
      provider: "npm"
      require: "Class[nodejs]"
    less: 
      ensure: "present"
      provider: "npm"
      require: "Class[nodejs]"
  php: 
    version: "55"
    composer: 1
    modules: 
      php: 
        - "cli"
        - "intl"
        - "mcrypt"
        - "gd"
        - "tidy"
        - "xcache"
        - "mbstring"
      pear: {}
      pecl: 
        - "pecl_http"
        - "mongo"
        - "redis"
        - "imagick"
        - "memcached"
        - "mosquitto"
    ini: 
      display_errors: "On"
      error_reporting: "-1"
      session.save_path: "/var/lib/php/session"
    timezone: "America/New_York"
  xdebug: 
    install: 1
    settings: 
      xdebug.default_enable: 1
      xdebug.remote_autostart: 0
      xdebug.remote_connect_back: 1
      xdebug.remote_enable: 1
      xdebug.remote_handler: "dbgp"
      xdebug.remote_port: "9000"
  xhprof: 
    install: 1
  drush: 
    install: 0
    settings: 
      drush.tag_branch: "6.x"
  mysql: 
    install: 1
    root_password: "rootPassword77"
    server_package_name: "MariaDB-server"
    client_package_name: "MariaDB-client"
    phpmyadmin: 1
    adminer: 1
    service_name: "mysql"
    service_enabled: true
    service_manage: true
    remove_default_accounts: true
    manage_config_file: true
    override_options: 
      mysqld: 
        pid-file: "/tmp/mysql.pid"
    databases: 
      SkzqECEhdnlw: 
        grant: 
          - "ALL"
        name: "dev"
        host: "localhost"
        user: "dev"
        password: "devPwD77"
        sql_file: false
      o12sfRpv6CHN: 
        grant: 
          - "ALL"
        name: "prod"
        host: "localhost"
        user: "prod"
        password: "prodPwD77"
        sql_file: false
  mongodb: 
    install: 1
    auth: 1
    port: "27017"
    databases: 
      LhqWcPiEO3P3: 
        name: "dev"
        user: "dev"
        password: "CocaCola77"
      4ur349R8u34r: 
        name: "prod"
        user: "prod"
        password: "CocaCola77"
  custom_repos: 
    mosquitto: 
      descr: "Mosquitto RHEL Repository"
      baseurl: "http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6/"
      gpgkey: "http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6/repodata/repomd.xml.key"
      enabled: 1
      gpgcheck: 1
      autokeyimport: "yes"
    mariadb: 
      descr: "MariaDB 10.0 repository"
      baseurl: "http://yum.mariadb.org/10.0/centos6-amd64"
      gpgkey: "https://yum.mariadb.org/RPM-GPG-KEY-MariaDB"
      enabled: 1
      gpgcheck: 1
  beanstalkd: 
    install: 0
    settings: 
      listenaddress: "0.0.0.0"
      listenport: "13000"
      maxjobsize: "65535"
      maxconnections: "1024"
      binlogdir: "/var/lib/beanstalkd/binlog"
      binlogfsync: null
      binlogsize: "10485760"
    beanstalk_console: 1
    binlogdir: "/var/lib/beanstalkd/binlog"
  rabbitmq: 
    install: 0
    port: "5672"
  elastic_search: 
    install: 1
  firewall: 
    setup: 1
    rules: 
      006 nginx-http-https: 
        ensure: "present"
        port: 
          - 80
          - 443
        proto: "tcp"
        action: "accept"
        destination: "%{::ipaddress_eth0}"
      002 accept related established rules: 
        proto: "all"
        ctstate: 
          - "RELATED"
          - "ESTABLISHED"
        action: "accept"
